version: '3'

services:
  # simpleclip:
  #   build: .
  #   image: simpleclip:latest
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./app:/app/app
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   environment:
  #     - MODEL_PATH=/app/utils/simple_clip/models/clip_model.pth
  #     - IMAGE_ENCODER=mobile_net_v3_small
  #     - TEXT_ENCODER=phobert-base
  #   command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8081", "--reload"]

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.1
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'

# Add this volumes section to define weaviate_data
volumes:
  weaviate_data: